# The schema of a master config file.
type: map
mapping:
  "base_path":
    type: str
    required: no
  "logger":
    type: map
    required: yes
    mapping:
      "path":
        type: str
        required: yes
      "level":
        type: str
        required: yes
        enum: [FATAL, ERROR, WARN, INFO, DEBUG]

  "su":
    type: seq
    required: yes
    sequence:
      - type: str

  "authn":
    type: map
    required: yes
    mapping:
      "htdigest":
        type: str
        required: yes
      "realm":
        type: str
        required: yes
      "admin":
        type: str
        required: yes

  "authn_account":
    type: map
    required: no
    mapping:
      "htdigest":
        type: str
        required: yes
      "realm":
        type: str
        required: yes
      "user":
        type: str
        required: yes
      "passwd":
        type: str
        required: yes

  "mail":
    type: map
    required: no
    mapping:
     "addres":
       type: str
       required: no
     "port":
       type: int
       required: no
     "domain":
       type: str
       required: no
     "authentication":
       type: str
       required: no
     "user_name":
       type: str
       required: no
     "password":
       type: str
       reqruied: no

  "record":
    type: map
    required: yes
    mapping:
      "show_login":
        type: bool
        required: yes
      "open":
        type: bool
        required: yes
      "detail":
        type: str
      "reload":
        type: int

  "comment":
    type: map
    required: yes
    mapping:
      "enable":
        type: bool
        required: yes

  "interact":
    type: map
    mapping:
      "default":
        type: map
        required: yes
        mapping:
          "sandbox":
            type: str
            required: yes
          "run": &run
            type: seq
            sequence:
              - type: str
      =:
        type: map
        mapping:
          "run": &run

  "check":
    type: map
    required: yes
    mapping:
      "default":
        type: map
        required: yes
        mapping:
          "require": &require
            type: seq
            sequence:
              - type: str
          "ignore": &ignore
            type: seq
            sequence:
              - type: str
          "applet":
            type: map
            mapping:
              "java_library":
                type: seq
                sequence:
                  - type: str
              "width":
                type: int
              "height":
                type: int
          "test":
            type: map
            mapping:
              "files":
                type: seq
                required: yes
                sequence:
                  - type: str
              "input":
                type: str
                required: yes
              "output":
                type: any # TODO: specify as symbol or str
                required: yes
              "sandbox":
                type: str
                required: yes
              "run":
                type: str
                required: yes
          "build":
            type: map
            required: yes
            mapping:
              "command": &command
                type: seq
                sequence:
                  - type: str
              "file_location": &file_location
                type: seq
                sequence:
                  - type: map
                    mapping:
                      "exercise":
                        type: seq
                        sequence:
                          - type: str
                            required: yes
                      "location":
                        type: str
                        required: yes
      =:
        type: map
        mapping:
          "require": *require
          "ignore": *ignore
          "test":
            type: map
            mapping:
              "run":
                type: str
          "build":
            type: map
            mapping:
              "command": *command
              "file_location": *file_location
